### ISSUE TITLE
 Worlds

### ISSUE THREAD

**Issue by OverBrave** [BentoBoxWorld/Boxed#15]
6 different world files are created in the server files.

![image](https://user-images.githubusercontent.com/47111280/112875699-2f3aa500-90cd-11eb-9ae7-7a7d94e7a804.png)

Bentobox version 1.16.1
Boxed version 1.0.4

**Comment by fredthedoggy** [comment]
That is normal behavior, `_bak` worlds are how the regular worlds are generated

**Comment by OverBrave** [comment]
Why are these files not available for other worlds?

**Comment by fredthedoggy** [comment]
Because vanilla-ish worlds are not created for other gamemodes

**Comment by OverBrave** [comment]
So do these worlds affect server performance?
And do they take up extra space?

**Comment by fredthedoggy** [comment]
Yes they take up space, yes they will take up a tiny bit of performance, but otherwise Boxed will not work.

**Comment by OverBrave** [comment]
I mean, the more chunks open, the more space the world files take up. Is the same for _bak files? And does it make a performance problem for 85 players?

**Comment by fredthedoggy** [comment]
It will take up more space, correct. but it is needed for boxed to function

**Comment by OverBrave** [comment]
I did not get the exact answer I wanted. Let me ask like this.

Question 1:
If a world "boxed_world" spends 50GB, how much space does the "boxed_world_bak" world spend?

Question 2:
What performance problems can this incident cause on an 85-person server?

3. Does RAM consumption increase?

**Comment by fredthedoggy** [comment]
1. if you have many 1,000's of islands that take of 50gb, Your back world will take about 20-40 gb I'd guess.
2. There is very little performance drop
3. Yes, but not by very much

**Comment by OverBrave** [comment]
So if there are 1000 islands, (Considering that a new player always comes and opens an island, this number is very low.)
boxed_world and boxed_world_bak will take up 90GB of space in total, which is really a lot. In my opinion, a different method needs to be found in order to make this mode more useful.

**Comment by fredthedoggy** [comment]
1000 players is not gonna take up 90gb. my guess is it would take up about 6gb.

**Comment by OverBrave** [comment]
Got it, this is for all sizes. Okay then it doesn't seem like much trouble. I hope there will be no problems in the future.

**Comment by tastybento** [comment]
The _bak world only is used when the player's area is reset. Until that happens, no chunks are generated in it. So, if no one ever reset their area then the _bak world would stay really tiny - just a few chunks. Further, when the player does reset, only the chunks where they had access are generated in the _bak file. That may be just a few chunks. Finally, as areas are always generated near the center of the world (after each server reset the server tries to use holes from the center) then the _bak world will probably be mostly static after a while.
Other info:

- The -bak world is set to peaceful. There should be no mobs there (monsters)
- No one ever should ever go to those worlds. Even admins.
- It is absolutely fine to delete those worlds if you think they are too big. The chunks will be regenerated when your players reset. However, keeping them there will speed up deletion because the chunks won't need to be generated.
- The server should not load more than just the spawn chunks of the world and if you have a way to prevent even those to be loaded then that's fine.
- Right now, the End_bak is not used.

I hope that info helps.
