### ISSUE TITLE
 Nether portal is not working.

### ISSUE THREAD

**Issue by OverBrave** [BentoBoxWorld/Boxed#17]
#### Describe the bug
If we set the "allow-nether" setting to "false" from the server.properties file, we cannot use portals to go from our box to our nether box.

This problem was actually resolved beforehand:
https://github.com/BentoBoxWorld/BentoBox/issues/1527

(I could not try it in other game modes. So since I thought the problem was here, I decided to bring it up here.)

##### Output of `/bbox version` (Mandatory)

```
Bentobox 1.16.1
Boxed 1.0.4
```

**Comment by fredthedoggy** [comment]
If theres no nether, then well... there's no nether? 
Whats the issue here

**Comment by OverBrave** [comment]
The setting inside the server.properties file allows the nether world to be created for the normal world. I close it because I don't want it to be created. If you examine the issue I posted, you can fully understand the problem.

**Comment by fredthedoggy** [comment]
Server.properties disables the nether and nether portals, so it they will not work

**Comment by OverBrave** [comment]
Excatly yes but @tastybento fix this issue before.

**Comment by tastybento** [comment]
Well, there's a conflict. For the Boxed nether teleporting we're using the server default teleportation (`create-and-link-portals: true`) - that's the setting in the config. We're doing this because it finds a safe spot and makes a portal and it's all vanilla. If you turn that off at the server level then that's why it doesn't work.

You can try setting that to false, but I'm pretty sure you won't get an obsidian portal generated. I can't test right now, but try it and let me know what happens.

**Comment by OverBrave** [comment]
Yes, I was teleported when I turned off the "create-and-link-portals:" setting, but I was spawn on bedrocks.
![image](https://user-images.githubusercontent.com/47111280/113470947-ca32d680-9461-11eb-938a-6cb138469dcc.png)

**Comment by tastybento** [comment]
Try with the latest snapshot of BentoBox and Boxed 1.0.4. Also, make sure you delete the Boxed blueprints folder so new ones are generated.

**Comment by tastybento** [comment]
This is because of the SafeSpotTeleport algorithm. It doesn't "know" about Nether roofs that are lower than the world max height. It needs rewriting.

**Comment by tastybento** [comment]
Old issue. Fixed (I think).
