### ISSUE TITLE
Caves and Cliffs will be added?

### ISSUE THREAD

**Issue by OverBrave** [BentoBoxWorld/Boxed#28]
World biomes are being formed straight. There is a not bad world, formation to ease your gameplay. But will "Caves and Cliffs" be added to the world formation in the "Caves and Cliffs" update?

**Comment by tastybento** [comment]
I don't know. The caves may happen automatically. The above-ground terrain will probably not happen because Boxed uses a custom made terrain algorithm that ensures everyone gets roughly the same terrain. It's quite a simple one too. The Caves and Cliffs will use their own sophisticated algorithms which might become available in the WorldGeneratorAPI. I'm not sure. We'll have to see!

**Comment by tastybento** [comment]
Supported in latest release.
